import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Veste en Sweat',
      slug: 'veste-en-Sweat',
      category: 'Shirts',
      image: '/images/VesteSweat.jpg',
      price: 980,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Sweat West',
      isFeatured: false,
      banner: '/images/VesteSweat.jpg',
    },
    {
      name: 'Redbrige Sweat',
      slug: 'redbrige-sweat',
      category: 'Shirts',
      image: '/images/RedbrigeSweat.jpg',
      price: 870,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Sweat',
      isFeatured: false,
      banner: '/images/RedbrigeSweat.jpg',
    },
    // {
    //   name: 'Jesheridan Shirt',
    //   slug: 'jesheridan-shirt',
    //   category: 'Shirts',
    //   image: '/images/JesheridanShirt.jpg',
    //   price: 300,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 8,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    //   isFeatured: true,
    //   banner: '/images/JesheridanShirt.jpg',
    // },
    {
      name: 'Jack Jones Sweat',
      slug: 'jack-jones-sweat',
      category: 'Shirts',
      image: '/images/JackJones.jpg',
      price: 400,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Jack Jones Sweat',
      isFeatured: true,
      banner: '/images/JackJones.jpg',
    },
    {
      name: 'Sweat En Cotten',
      slug: 'sweat-en-cotton',
      category: 'Shirts',
      image: '/images/VesteSweat.jpg',
      price: 100,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Sweat West',
      isFeatured: false,
      banner: '/images/VesteSweat.jpg',
    },
    // {
    //   name: 'Jack and Jones Hommes',
    //   slug: 'jack-and-jones-hommes',
    //   category: 'Shirts',
    //   image: '/images/JackHommes.jpg',
    //   price: 100,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 8,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    //   isFeatured: true,
    //   banner: '/images/JackHommes.jpg',
    // },
    // {
    //   name: 'Bridge Pull',
    //   slug: 'bridge-pull',
    //   category: 'Shirts',
    //   image: '/images/Bridge.jpg',
    //   price: 900,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 8,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    //   isFeatured: true,
    //   banner: '/images/Bridge.jpg',
    // },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
